services:
  devcontainer:
    command: sh -c 'while sleep 1; do :; done'
    image: ghcr.io/acilearning/docker-haskell:9.2.4
    volumes:
      - .:/workspaces/monadoc
    working_dir: /workspaces/monadoc
