services:
  devcontainer:
    build: docker/devcontainer
    command: sh -c 'while sleep 1; do :; done'
    volumes:
      - .:/workspaces/monadoc
      - ./.cabal:/root/.cabal
    working_dir: /workspaces/monadoc
