services:
  devcontainer:
    command: sh -c 'while sleep 1; do :; done'
    image: public.ecr.aws/acilearning/haskell:9.4.4
    volumes:
      - .:/workspaces/monadoc
    working_dir: /workspaces/monadoc
