services:
  devcontainer:
    command: sh -c 'while sleep 1; do :; done'
    image: public.ecr.aws/v6m6o3k4/haskell:9.4.2-a853e18e0505bc9590dd6eaa31231ae2610fbfa8
    volumes:
      - .:/workspaces/monadoc
    working_dir: /workspaces/monadoc
