services:
  devcontainer:
    build: docker/devcontainer
    command: sh -c 'while sleep 1; do :; done'
    init: true
    volumes:
      - .:/workspaces/monadoc
      - cabal:/home/haskell/.cabal
    working_dir: /workspaces/monadoc
volumes:
  cabal: null
