[env]
GHCRTS = "-K1k -M1g"
MONADOC_BASE_URL = "https://monadoc.com"

[mounts]
destination = "/home/monadoc/volume"
source = "monadoc_volume"

[[services]]
internal_port = 8080
protocol = "tcp"

[[services.http_checks]]
path = "/health-check"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443
