{
  "services": {
    "devcontainer": {
      "command": "sleep infinity",
      "image": "public.ecr.aws/acilearning/haskell:9.8.1",
      "init": true,
      "volumes": [
        "..:/workspace",
        "cabal-cache:/home/vscode/.cache/cabal",
        "cabal-state:/home/vscode/.local/state/cabal",
      ],
      "working_dir": "/workspace"
    }
  },
  "volumes": {
    "cabal-cache": null,
    "cabal-state": {
      "external": true
    }
  }
}
