version: '3.8'
services:
  devcontainer:
    build: .
    command: sh -c 'while :; do sleep 60; done'
    image: monadoc
    init: true
    ports:
      - 3000:3000
    volumes:
      - ..:/workspaces/monadoc:cached
      - cabal:/home/haskell/.cabal:cached
      - cabal-store:/cabal-store:cached
    working_dir: /workspaces/monadoc
volumes:
  cabal: null
  cabal-store:
    external: true
