name: Workflow
on: push
jobs:
  job:
    strategy:
      matrix:
        platform:
          - macos
          - ubuntu
          - windows
    runs-on: ${{ matrix.platform }}-latest
    name: Job on ${{ matrix.platform }}
    steps:

      - uses: actions/checkout@v2

      - id: artifact
        run: |
          mkdir artifact
          mkdir artifact/${{ matrix.platform }}
          echo '::set-output name=directory::artifact/${{ matrix.platform }}'

      - id: setup-haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: 9.2.1

      - run: cabal configure --enable-tests --flags pedantic --jobs

      - run: cp cabal.project.local ${{ steps.artifact.outputs.directory }}

      - run: cabal freeze

      - run: cat cabal.project.freeze

      - run: cp cabal.project.freeze ${{ steps.artifact.outputs.directory }}

      - uses: actions/cache@v2
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ matrix.platform }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: ${{ matrix.platform }}-

      - run: cabal build

      - run: cp "$( cabal list-bin monadoc )" ${{ steps.artifact.outputs.directory }}

      - shell: bash
        run: $( cabal list-bin monadoc-test-suite )

      - run: cabal sdist --output-dir ${{ steps.artifact.outputs.directory }}

      - run: cabal check

      - uses: actions/upload-artifact@v2
        with:
          name: monadoc-${{ github.sha }}
          path: artifact
